### ISSUE TITLE
Any idea! what should we keep in Dashboard? Any information would be a great help.

### ISSUE THREAD

**Issue by Sandesh-Ghimire** [aashish-pandey/VideoStreamingWebApp#2]
Can anyone give the wireframe or any sort of design for Dashboard?

**Comment by aashish-pandey** [comment]
Number of cards that will have the point graphs which will demonstrate the statistics of number of activities related to that card. For eg: we have a user login stats card. we will count how many times login have been done in the day and plot that point. we will show the point for each day (like nepse chart). Same for number of movie uploads, new user registers, chats posted, etc.

**Comment by Sandesh-Ghimire** [comment]
Thanks for the idea. We will work on it.
